// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm5oz5kHuttJMxDKJM2xXa4f3BsBgCs-o',
    appId: '1:199230236197:web:d98ac085e6c1e9691981cc',
    messagingSenderId: '199230236197',
    projectId: 'restaurant-system-d9536',
    authDomain: 'restaurant-system-d9536.firebaseapp.com',
    storageBucket: 'restaurant-system-d9536.firebasestorage.app',
    measurementId: 'G-Z0QKQZ0QQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCudhxROrkASSIH-ndOlbtELZm6FaEuwW8',
    appId: '1:199230236197:android:a13afb583dba57321981cc',
    messagingSenderId: '199230236197',
    projectId: 'restaurant-system-d9536',
    storageBucket: 'restaurant-system-d9536.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZwaFoprw9s_BxQ11pLjOpLHsczLyNig',
    appId: '1:199230236197:ios:8fd095033f01da521981cc',
    messagingSenderId: '199230236197',
    projectId: 'restaurant-system-d9536',
    storageBucket: 'restaurant-system-d9536.firebasestorage.app',
    iosBundleId: 'com.example.restaurantSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZwaFoprw9s_BxQ11pLjOpLHsczLyNig',
    appId: '1:199230236197:ios:8fd095033f01da521981cc',
    messagingSenderId: '199230236197',
    projectId: 'restaurant-system-d9536',
    storageBucket: 'restaurant-system-d9536.firebasestorage.app',
    iosBundleId: 'com.example.restaurantSystem',
  );
}
